/* tpconnect.c generated by valac 0.48.6, the Vala compiler
 * generated from tpconnect.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <stdio.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

gint _vala_main (gchar** args,
                 gint args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                        gpointer self);
static void ___lambda4_ (void);
static void ____lambda4__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
_gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                   gpointer self)
{
	gtk_main_quit ();
}

static void
___lambda4_ (void)
{
	gtk_main_quit ();
}

static void
____lambda4__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
	___lambda4_ ();
}

gint
_vala_main (gchar** args,
            gint args_length1)
{
	GError* _inner_error0_ = NULL;
	gint result = 0;
	gtk_init ((gint*) (&args_length1), &args);
	{
		GtkBuilder* builder = NULL;
		GtkBuilder* _tmp0_;
		GtkBuilder* _tmp1_;
		GtkComboBoxText* serverList = NULL;
		GtkBuilder* _tmp2_;
		GObject* _tmp3_;
		GtkComboBoxText* _tmp4_;
		GtkLabel* wrongLabel = NULL;
		GtkBuilder* _tmp5_;
		GObject* _tmp6_;
		GtkLabel* _tmp7_;
		GtkButton* settingsButton = NULL;
		GtkBuilder* _tmp8_;
		GObject* _tmp9_;
		GtkButton* _tmp10_;
		GtkBuilder* _tmp11_;
		GtkWindow* window = NULL;
		GtkBuilder* _tmp12_;
		GObject* _tmp13_;
		GtkWindow* _tmp14_;
		GtkWindow* _tmp15_;
		GtkButton* _tmp16_;
		GtkLabel* _tmp17_;
		GtkWindow* _tmp18_;
		_tmp0_ = gtk_builder_new ();
		builder = _tmp0_;
		_tmp1_ = builder;
		gtk_builder_add_from_file (_tmp1_, "connect-manager.glade", &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (builder);
			goto __catch0_g_error;
		}
		_tmp2_ = builder;
		_tmp3_ = gtk_builder_get_object (_tmp2_, "serverSelect");
		_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, gtk_combo_box_text_get_type ()) ? ((GtkComboBoxText*) _tmp3_) : NULL);
		serverList = _tmp4_;
		_tmp5_ = builder;
		_tmp6_ = gtk_builder_get_object (_tmp5_, "wrongLabel");
		_tmp7_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp6_) : NULL);
		wrongLabel = _tmp7_;
		_tmp8_ = builder;
		_tmp9_ = gtk_builder_get_object (_tmp8_, "settingsButton");
		_tmp10_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp9_, gtk_button_get_type ()) ? ((GtkButton*) _tmp9_) : NULL);
		settingsButton = _tmp10_;
		_tmp11_ = builder;
		gtk_builder_connect_signals (_tmp11_, NULL);
		_tmp12_ = builder;
		_tmp13_ = gtk_builder_get_object (_tmp12_, "thinpiMain");
		_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp13_) : NULL);
		window = _tmp14_;
		_tmp15_ = window;
		g_signal_connect ((GtkWidget*) _tmp15_, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
		_tmp16_ = settingsButton;
		g_signal_connect (_tmp16_, "clicked", (GCallback) ____lambda4__gtk_button_clicked, NULL);
		_tmp17_ = wrongLabel;
		gtk_widget_hide ((GtkWidget*) _tmp17_);
		_tmp18_ = window;
		gtk_window_fullscreen (_tmp18_);
		gtk_main ();
		_g_object_unref0 (window);
		_g_object_unref0 (settingsButton);
		_g_object_unref0 (wrongLabel);
		_g_object_unref0 (serverList);
		_g_object_unref0 (builder);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp19_;
		GError* _tmp20_;
		const gchar* _tmp21_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp19_ = stderr;
		_tmp20_ = e;
		_tmp21_ = _tmp20_->message;
		fprintf (_tmp19_, "Could not load ThinPi UI: %s\n", _tmp21_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gint _tmp22_ = -1;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp22_;
	}
	result = 0;
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

