#!/bin/bash

RED='\033[0;31m'
BLUE='\033[1;34m'

echo ""
echo -e "${RED}Creating /thinpi ..."
echo ""
sudo mkdir -p /thinpi
echo -e "${RED}Changing /thinpi permissions ..."
echo ""
sudo chmod 0777 /thinpi
echo -e "${RED}Current User: ${BLUE}$USER"
echo -e "${RED}Changing Ownership of /thinpi to ${BLUE}$USER"
echo ""
sudo chown $USER:$USER /thinpi