#!/bin/bash

wget https://kmprojects.us/tpupdate/version.tpv -o /tmp/version.tpv

file1="/tmp/version.tpv"
file2="/thinpi/version.tpv"

if cmp -s "$file1" "$file2"; then
    printf 'The file "%s" is the same as "%s"\n' "$file1" "$file2"
else
    printf 'The file "%s" is different from "%s"\n' "$file1" "$file2"
    dialog --title "tpupdate" --msgbox 'ThinPi has an update available' 6 20
fi
