#!/bin/bash

wget -q https://kmprojects.us/api/tp/update.txt -O /tmp/version.tpv
echo "Checking for updates...."
sleep 2;

file1="/usr/bin/update.txt"
file2="/thinpi/version.tpv"

version="0.2-h1"
newversion=$(cat /tmp/version.tpv)
if [ "$version" == "$(cat /tmp/version.tpv)" ] ;then
    echo "ThinPi is Up to Date - $version"
else
    echo "ThinPi has a Update Current version: $version - Update version: $newversion"
fi
